name: Test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    run:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            max-parallel: 2
            matrix:
                operating-system:
                    - ubuntu-latest
                php-versions:
                    - 7.2
                    - 7.3
                    - 7.4
                    - 8.0
        name: PHP ${{ matrix.php-versions }} test on ${{ matrix.operating-system }}
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: ${{ matrix.php-versions }}
                  coverage: xdebug
            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer
            - name: Install Composer dependencies
              run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
            - name: Testing with PHPUnit
              run: vendor/bin/phpunit
